# Generated by Django 4.2.4 on 2023-08-29 13:10

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import trombinoscope.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', trombinoscope.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bac_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1984)], verbose_name='Année du bac'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='confirmed_account',
            field=models.BooleanField(default=False, verbose_name='compte confirmé'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_info_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse email de contact'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_info_instagram',
            field=models.URLField(blank=True, verbose_name='Compte instagram'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_info_linkedin',
            field=models.URLField(blank=True, verbose_name='Adresse profil linkedin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_info_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='FR'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enseignant_hida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='looking_for_internship',
            field=models.BooleanField(default=False, verbose_name='En recherche de stage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ET', 'Étudiant·e'), ('SA', 'Salarié·e'), ('IN', 'Indépendant·e'), ('EN', 'En recherche')], default='ET', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
