# Generated by Django 4.2.4 on 2023-09-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
