# Generated by Django 4.2.4 on 2023-09-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='mediafiles'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('ET', 'Étudiant·e'), ('SA', 'Salarié·e'), ('IN', 'Indépendant·e'), ('EN', 'En recherche')], default='ET', max_length=2, verbose_name='Statut'),
        ),
    ]
