# Generated by Django 4.2.4 on 2023-09-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0007_remove_customuser_enseignant_hida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='post_bac',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Études post Bac'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Emploi'),
        ),
    ]
