# Generated by Django 4.2.4 on 2023-09-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0008_customuser_post_bac_alter_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='occupation',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_bac',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Études après le Bac'),
        ),
    ]
