# Generated by Django 4.2.4 on 2023-10-31 10:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trombinoscope', '0014_alter_customuser_contact_info_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='occupation',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, verbose_name='Emploi'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_bac',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, verbose_name='Études après le Bac'),
        ),
    ]
